### PR TITLE
Julia 0.7/1.0

### PR DESCRIPTION
**Pull request by scls19fr**
Just a very simple PR to trigger FemtoCleaner (if enabled)

### CODE REVIEW

**Comment by scls19fr** [comment]
I don't think https://github.com/JuliaComputing/FemtoCleaner.jl is enabled here

**Comment by yuyichao** [comment]
The simple part are already ready in other PRs.

**Comment by scls19fr** [comment]
Thanks @yuyichao for your quick answer.
But could you enable FemtoCleaner?

**Comment by yuyichao** [comment]
I believe it is installed.

**Pull request closed without merging**
